[package]
name = "zkp-chaum-pedersen"
version = "0.1.0"
authors = ["ShuangWu121 <shuang.wu@posteo.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = { version = "0.4", features = ["rand"]}
